-- Focus Zone persistence schema
-- Run in Supabase SQL editor

-- 1) Core tables
create table if not exists public.user_challenge_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_id text not null,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, challenge_id)
);

create table if not exists public.pomodoro_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  duration_seconds integer not null check (duration_seconds > 0),
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.custom_challenges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) >= 3),
  target_sessions integer not null check (target_sessions > 0),
  points integer not null check (points > 0),
  is_group boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.reward_catalog (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  cost_points integer not null check (cost_points > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.reward_redemptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reward_id bigint not null references public.reward_catalog(id) on delete restrict,
  points_spent integer not null check (points_spent > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.user_rewards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) >= 3),
  description text not null default '',
  cost_points integer not null check (cost_points > 0),
  created_at timestamptz not null default now(),
  unique (user_id, title)
);

create table if not exists public.user_leaderboard (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  total_points integer not null default 0 check (total_points >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.pomodoro_rooms (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) >= 3),
  created_at timestamptz not null default now()
);

create table if not exists public.pomodoro_room_members (
  room_id bigint not null references public.pomodoro_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  joined_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create table if not exists public.pomodoro_room_presence (
  room_id bigint not null references public.pomodoro_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  time_left integer not null check (time_left >= 0),
  is_active boolean not null default false,
  is_paused boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

-- 2) Enable RLS
alter table public.user_challenge_progress enable row level security;
alter table public.pomodoro_sessions enable row level security;
alter table public.custom_challenges enable row level security;
alter table public.reward_catalog enable row level security;
alter table public.reward_redemptions enable row level security;
alter table public.user_rewards enable row level security;
alter table public.user_leaderboard enable row level security;
alter table public.pomodoro_rooms enable row level security;
alter table public.pomodoro_room_members enable row level security;
alter table public.pomodoro_room_presence enable row level security;

-- 3) user_challenge_progress policies
drop policy if exists "challenge_select_own" on public.user_challenge_progress;
drop policy if exists "challenge_insert_own" on public.user_challenge_progress;
drop policy if exists "challenge_update_own" on public.user_challenge_progress;
drop policy if exists "challenge_delete_own" on public.user_challenge_progress;

create policy "challenge_select_own"
  on public.user_challenge_progress
  for select
  using (auth.uid() = user_id);

create policy "challenge_insert_own"
  on public.user_challenge_progress
  for insert
  with check (auth.uid() = user_id);

create policy "challenge_update_own"
  on public.user_challenge_progress
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "challenge_delete_own"
  on public.user_challenge_progress
  for delete
  using (auth.uid() = user_id);

-- 4) pomodoro_sessions policies
drop policy if exists "pomodoro_select_own" on public.pomodoro_sessions;
drop policy if exists "pomodoro_insert_own" on public.pomodoro_sessions;
drop policy if exists "pomodoro_update_own" on public.pomodoro_sessions;
drop policy if exists "pomodoro_delete_own" on public.pomodoro_sessions;

create policy "pomodoro_select_own"
  on public.pomodoro_sessions
  for select
  using (auth.uid() = user_id);

create policy "pomodoro_insert_own"
  on public.pomodoro_sessions
  for insert
  with check (auth.uid() = user_id);

create policy "pomodoro_update_own"
  on public.pomodoro_sessions
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "pomodoro_delete_own"
  on public.pomodoro_sessions
  for delete
  using (auth.uid() = user_id);

-- 5) custom_challenges policies
drop policy if exists "custom_challenges_select_own" on public.custom_challenges;
drop policy if exists "custom_challenges_insert_own" on public.custom_challenges;
drop policy if exists "custom_challenges_update_own" on public.custom_challenges;
drop policy if exists "custom_challenges_delete_own" on public.custom_challenges;

create policy "custom_challenges_select_own"
  on public.custom_challenges
  for select
  using (auth.uid() = user_id);

create policy "custom_challenges_insert_own"
  on public.custom_challenges
  for insert
  with check (auth.uid() = user_id);

create policy "custom_challenges_update_own"
  on public.custom_challenges
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "custom_challenges_delete_own"
  on public.custom_challenges
  for delete
  using (auth.uid() = user_id);

-- 6) reward_catalog policies (catalog read-only for authenticated)
drop policy if exists "reward_catalog_select_authenticated" on public.reward_catalog;
drop policy if exists "reward_catalog_no_insert" on public.reward_catalog;
drop policy if exists "reward_catalog_no_update" on public.reward_catalog;
drop policy if exists "reward_catalog_no_delete" on public.reward_catalog;

create policy "reward_catalog_select_authenticated"
  on public.reward_catalog
  for select
  to authenticated
  using (is_active = true);

-- Explicit deny writes from anon/authenticated clients (service role can still write)
create policy "reward_catalog_no_insert"
  on public.reward_catalog
  for insert
  to authenticated
  with check (false);

create policy "reward_catalog_no_update"
  on public.reward_catalog
  for update
  to authenticated
  using (false)
  with check (false);

create policy "reward_catalog_no_delete"
  on public.reward_catalog
  for delete
  to authenticated
  using (false);

-- 7) reward_redemptions policies
drop policy if exists "reward_redemptions_select_own" on public.reward_redemptions;
drop policy if exists "reward_redemptions_insert_own" on public.reward_redemptions;
drop policy if exists "reward_redemptions_update_own" on public.reward_redemptions;
drop policy if exists "reward_redemptions_delete_own" on public.reward_redemptions;

create policy "reward_redemptions_select_own"
  on public.reward_redemptions
  for select
  using (auth.uid() = user_id);

create policy "reward_redemptions_insert_own"
  on public.reward_redemptions
  for insert
  with check (auth.uid() = user_id);

create policy "reward_redemptions_update_own"
  on public.reward_redemptions
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "reward_redemptions_delete_own"
  on public.reward_redemptions
  for delete
  using (auth.uid() = user_id);

-- 8) user_rewards policies
drop policy if exists "user_rewards_select_own" on public.user_rewards;
drop policy if exists "user_rewards_insert_own" on public.user_rewards;
drop policy if exists "user_rewards_update_own" on public.user_rewards;
drop policy if exists "user_rewards_delete_own" on public.user_rewards;

create policy "user_rewards_select_own"
  on public.user_rewards
  for select
  using (auth.uid() = user_id);

create policy "user_rewards_insert_own"
  on public.user_rewards
  for insert
  with check (auth.uid() = user_id);

create policy "user_rewards_update_own"
  on public.user_rewards
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "user_rewards_delete_own"
  on public.user_rewards
  for delete
  using (auth.uid() = user_id);

-- 9) user_leaderboard policies
drop policy if exists "leaderboard_select_authenticated" on public.user_leaderboard;
drop policy if exists "leaderboard_select_public" on public.user_leaderboard;
drop policy if exists "leaderboard_insert_own" on public.user_leaderboard;
drop policy if exists "leaderboard_update_own" on public.user_leaderboard;
drop policy if exists "leaderboard_delete_own" on public.user_leaderboard;

create policy "leaderboard_select_public"
  on public.user_leaderboard
  for select
  to public
  using (true);

create policy "leaderboard_insert_own"
  on public.user_leaderboard
  for insert
  with check (auth.uid() = user_id);

create policy "leaderboard_update_own"
  on public.user_leaderboard
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "leaderboard_delete_own"
  on public.user_leaderboard
  for delete
  using (auth.uid() = user_id);

-- 10) pomodoro_rooms policies
drop policy if exists "pomodoro_rooms_select_authenticated" on public.pomodoro_rooms;
drop policy if exists "pomodoro_rooms_insert_own" on public.pomodoro_rooms;
drop policy if exists "pomodoro_rooms_update_owner" on public.pomodoro_rooms;
drop policy if exists "pomodoro_rooms_delete_owner" on public.pomodoro_rooms;

create policy "pomodoro_rooms_select_authenticated"
  on public.pomodoro_rooms
  for select
  to authenticated
  using (true);

create policy "pomodoro_rooms_insert_own"
  on public.pomodoro_rooms
  for insert
  with check (auth.uid() = owner_id);

create policy "pomodoro_rooms_update_owner"
  on public.pomodoro_rooms
  for update
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

create policy "pomodoro_rooms_delete_owner"
  on public.pomodoro_rooms
  for delete
  using (auth.uid() = owner_id);

-- 11) pomodoro_room_members policies
drop policy if exists "pomodoro_room_members_select_authenticated" on public.pomodoro_room_members;
drop policy if exists "pomodoro_room_members_insert_own" on public.pomodoro_room_members;
drop policy if exists "pomodoro_room_members_update_own" on public.pomodoro_room_members;
drop policy if exists "pomodoro_room_members_delete_own_or_owner" on public.pomodoro_room_members;

create policy "pomodoro_room_members_select_authenticated"
  on public.pomodoro_room_members
  for select
  to authenticated
  using (true);

create policy "pomodoro_room_members_insert_own"
  on public.pomodoro_room_members
  for insert
  with check (auth.uid() = user_id);

create policy "pomodoro_room_members_update_own"
  on public.pomodoro_room_members
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "pomodoro_room_members_delete_own_or_owner"
  on public.pomodoro_room_members
  for delete
  using (
    auth.uid() = user_id
    or exists (
      select 1
      from public.pomodoro_rooms r
      where r.id = room_id
        and r.owner_id = auth.uid()
    )
  );

-- 12) pomodoro_room_presence policies
drop policy if exists "pomodoro_room_presence_select_authenticated" on public.pomodoro_room_presence;
drop policy if exists "pomodoro_room_presence_insert_own" on public.pomodoro_room_presence;
drop policy if exists "pomodoro_room_presence_update_own" on public.pomodoro_room_presence;
drop policy if exists "pomodoro_room_presence_delete_own" on public.pomodoro_room_presence;

create policy "pomodoro_room_presence_select_authenticated"
  on public.pomodoro_room_presence
  for select
  to authenticated
  using (true);

create policy "pomodoro_room_presence_insert_own"
  on public.pomodoro_room_presence
  for insert
  with check (auth.uid() = user_id);

create policy "pomodoro_room_presence_update_own"
  on public.pomodoro_room_presence
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "pomodoro_room_presence_delete_own"
  on public.pomodoro_room_presence
  for delete
  using (auth.uid() = user_id);

-- 5) Indexes
create index if not exists idx_user_challenge_progress_user_id on public.user_challenge_progress (user_id);
create index if not exists idx_user_challenge_progress_completed_at on public.user_challenge_progress (completed_at desc);
create index if not exists idx_pomodoro_sessions_user_id on public.pomodoro_sessions (user_id);
create index if not exists idx_pomodoro_sessions_completed_at on public.pomodoro_sessions (completed_at desc);
create index if not exists idx_custom_challenges_user_id on public.custom_challenges (user_id);
create index if not exists idx_reward_redemptions_user_id on public.reward_redemptions (user_id);
create index if not exists idx_reward_catalog_is_active on public.reward_catalog (is_active);
create index if not exists idx_user_rewards_user_id on public.user_rewards (user_id);
create index if not exists idx_user_leaderboard_points on public.user_leaderboard (total_points desc, updated_at asc);
create index if not exists idx_pomodoro_rooms_created_at on public.pomodoro_rooms (created_at desc);
create index if not exists idx_pomodoro_room_members_user on public.pomodoro_room_members (user_id);
create index if not exists idx_pomodoro_room_presence_updated_at on public.pomodoro_room_presence (updated_at desc);

delete from public.reward_catalog a
using public.reward_catalog b
where a.id > b.id
  and a.title = b.title;

create unique index if not exists idx_reward_catalog_title_unique on public.reward_catalog (title);

insert into public.reward_catalog (title, description, cost_points)
values
  ('Bono Kokoriko', 'Cupon de ejemplo para redimir en aliados.', 120),
  ('Tema premium', 'Desbloquea una apariencia premium en la app.', 80),
  ('Descanso extendido', 'Canjea un break de 30 minutos sin culpa.', 60)
on conflict (title) do nothing;

create or replace function public.get_email_by_nickname(nickname_input text)
returns text
language sql
security definer
set search_path = public, auth
as $$
  select email
  from auth.users
  where lower(coalesce(raw_user_meta_data->>'nickname', raw_user_meta_data->>'full_name', '')) = lower(nickname_input)
  limit 1;
$$;

revoke all on function public.get_email_by_nickname(text) from public;
grant execute on function public.get_email_by_nickname(text) to anon, authenticated;
