-- Focus Zone persistence schema
-- Run in Supabase SQL editor

-- 1) Core tables
create table if not exists public.user_challenge_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_id text not null,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, challenge_id)
);

create table if not exists public.pomodoro_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  duration_seconds integer not null check (duration_seconds > 0),
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.custom_challenges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) >= 3),
  target_sessions integer not null check (target_sessions > 0),
  points integer not null check (points > 0),
  is_group boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.reward_catalog (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  cost_points integer not null check (cost_points > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.reward_redemptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reward_id bigint not null references public.reward_catalog(id) on delete restrict,
  points_spent integer not null check (points_spent > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.user_rewards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) >= 3),
  description text not null default '',
  cost_points integer not null check (cost_points > 0),
  created_at timestamptz not null default now(),
  unique (user_id, title)
);

create table if not exists public.user_leaderboard (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  total_points integer not null default 0 check (total_points >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.pomodoro_rooms (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) >= 3),
  created_at timestamptz not null default now()
);

create table if not exists public.pomodoro_room_members (
  room_id bigint not null references public.pomodoro_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  joined_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create table if not exists public.pomodoro_room_presence (
  room_id bigint not null references public.pomodoro_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  time_left integer not null check (time_left >= 0),
  is_active boolean not null default false,
  is_paused boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create table if not exists public.challenge_catalog (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null check (char_length(title) >= 3),
  description text not null default '',
  week integer not null check (week between 1 and 3),
  day integer not null check (day between 1 and 21),
  points integer not null check (points > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  subscription jsonb not null,
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.auth_email_codes (
  id bigint generated by default as identity primary key,
  email text not null,
  purpose text not null check (purpose in ('signup', 'password_reset', 'verify_email')),
  code_hash text not null,
  metadata jsonb not null default '{}'::jsonb,
  attempts integer not null default 0,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_auth_email_codes_lookup
  on public.auth_email_codes (email, purpose, created_at desc);

-- 2) Enable RLS
alter table public.user_challenge_progress enable row level security;
alter table public.pomodoro_sessions enable row level security;
alter table public.custom_challenges enable row level security;
alter table public.reward_catalog enable row level security;
alter table public.reward_redemptions enable row level security;
alter table public.user_rewards enable row level security;
alter table public.user_leaderboard enable row level security;
alter table public.pomodoro_rooms enable row level security;
alter table public.pomodoro_room_members enable row level security;
alter table public.pomodoro_room_presence enable row level security;
alter table public.challenge_catalog enable row level security;
alter table public.push_subscriptions enable row level security;

-- 3) user_challenge_progress policies
drop policy if exists "challenge_select_own" on public.user_challenge_progress;
drop policy if exists "challenge_insert_own" on public.user_challenge_progress;
drop policy if exists "challenge_update_own" on public.user_challenge_progress;
drop policy if exists "challenge_delete_own" on public.user_challenge_progress;

create policy "challenge_select_own"
  on public.user_challenge_progress
  for select
  using (auth.uid() = user_id);

create policy "challenge_insert_own"
  on public.user_challenge_progress
  for insert
  with check (auth.uid() = user_id);

create policy "challenge_update_own"
  on public.user_challenge_progress
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "challenge_delete_own"
  on public.user_challenge_progress
  for delete
  using (auth.uid() = user_id);

-- 4) pomodoro_sessions policies
drop policy if exists "pomodoro_select_own" on public.pomodoro_sessions;
drop policy if exists "pomodoro_insert_own" on public.pomodoro_sessions;
drop policy if exists "pomodoro_update_own" on public.pomodoro_sessions;
drop policy if exists "pomodoro_delete_own" on public.pomodoro_sessions;

create policy "pomodoro_select_own"
  on public.pomodoro_sessions
  for select
  using (auth.uid() = user_id);

create policy "pomodoro_insert_own"
  on public.pomodoro_sessions
  for insert
  with check (auth.uid() = user_id);

create policy "pomodoro_update_own"
  on public.pomodoro_sessions
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "pomodoro_delete_own"
  on public.pomodoro_sessions
  for delete
  using (auth.uid() = user_id);

-- 5) custom_challenges policies
drop policy if exists "custom_challenges_select_own" on public.custom_challenges;
drop policy if exists "custom_challenges_insert_own" on public.custom_challenges;
drop policy if exists "custom_challenges_update_own" on public.custom_challenges;
drop policy if exists "custom_challenges_delete_own" on public.custom_challenges;

create policy "custom_challenges_select_own"
  on public.custom_challenges
  for select
  using (auth.uid() = user_id);

create policy "custom_challenges_insert_own"
  on public.custom_challenges
  for insert
  with check (auth.uid() = user_id);

create policy "custom_challenges_update_own"
  on public.custom_challenges
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "custom_challenges_delete_own"
  on public.custom_challenges
  for delete
  using (auth.uid() = user_id);

-- 6) reward_catalog policies (catalog read-only for authenticated)
drop policy if exists "reward_catalog_select_authenticated" on public.reward_catalog;
drop policy if exists "reward_catalog_no_insert" on public.reward_catalog;
drop policy if exists "reward_catalog_no_update" on public.reward_catalog;
drop policy if exists "reward_catalog_no_delete" on public.reward_catalog;

create policy "reward_catalog_select_authenticated"
  on public.reward_catalog
  for select
  to authenticated
  using (is_active = true);

-- Explicit deny writes from anon/authenticated clients (service role can still write)
create policy "reward_catalog_no_insert"
  on public.reward_catalog
  for insert
  to authenticated
  with check (false);

create policy "reward_catalog_no_update"
  on public.reward_catalog
  for update
  to authenticated
  using (false)
  with check (false);

create policy "reward_catalog_no_delete"
  on public.reward_catalog
  for delete
  to authenticated
  using (false);

-- 7) reward_redemptions policies
drop policy if exists "reward_redemptions_select_own" on public.reward_redemptions;
drop policy if exists "reward_redemptions_insert_own" on public.reward_redemptions;
drop policy if exists "reward_redemptions_update_own" on public.reward_redemptions;
drop policy if exists "reward_redemptions_delete_own" on public.reward_redemptions;

create policy "reward_redemptions_select_own"
  on public.reward_redemptions
  for select
  using (auth.uid() = user_id);

create policy "reward_redemptions_insert_own"
  on public.reward_redemptions
  for insert
  with check (auth.uid() = user_id);

create policy "reward_redemptions_update_own"
  on public.reward_redemptions
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "reward_redemptions_delete_own"
  on public.reward_redemptions
  for delete
  using (auth.uid() = user_id);

-- 8) user_rewards policies
drop policy if exists "user_rewards_select_own" on public.user_rewards;
drop policy if exists "user_rewards_insert_own" on public.user_rewards;
drop policy if exists "user_rewards_update_own" on public.user_rewards;
drop policy if exists "user_rewards_delete_own" on public.user_rewards;

create policy "user_rewards_select_own"
  on public.user_rewards
  for select
  using (auth.uid() = user_id);

create policy "user_rewards_insert_own"
  on public.user_rewards
  for insert
  with check (auth.uid() = user_id);

create policy "user_rewards_update_own"
  on public.user_rewards
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "user_rewards_delete_own"
  on public.user_rewards
  for delete
  using (auth.uid() = user_id);

-- 9) user_leaderboard policies
drop policy if exists "leaderboard_select_authenticated" on public.user_leaderboard;
drop policy if exists "leaderboard_select_public" on public.user_leaderboard;
drop policy if exists "leaderboard_insert_own" on public.user_leaderboard;
drop policy if exists "leaderboard_update_own" on public.user_leaderboard;
drop policy if exists "leaderboard_delete_own" on public.user_leaderboard;

create policy "leaderboard_select_public"
  on public.user_leaderboard
  for select
  to public
  using (true);

create policy "leaderboard_insert_own"
  on public.user_leaderboard
  for insert
  with check (auth.uid() = user_id);

create policy "leaderboard_update_own"
  on public.user_leaderboard
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "leaderboard_delete_own"
  on public.user_leaderboard
  for delete
  using (auth.uid() = user_id);

-- 10) pomodoro_rooms policies
drop policy if exists "pomodoro_rooms_select_authenticated" on public.pomodoro_rooms;
drop policy if exists "pomodoro_rooms_insert_own" on public.pomodoro_rooms;
drop policy if exists "pomodoro_rooms_update_owner" on public.pomodoro_rooms;
drop policy if exists "pomodoro_rooms_delete_owner" on public.pomodoro_rooms;

create policy "pomodoro_rooms_select_authenticated"
  on public.pomodoro_rooms
  for select
  to authenticated
  using (true);

create policy "pomodoro_rooms_insert_own"
  on public.pomodoro_rooms
  for insert
  with check (auth.uid() = owner_id);

create policy "pomodoro_rooms_update_owner"
  on public.pomodoro_rooms
  for update
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

create policy "pomodoro_rooms_delete_owner"
  on public.pomodoro_rooms
  for delete
  using (auth.uid() = owner_id);

-- 11) pomodoro_room_members policies
drop policy if exists "pomodoro_room_members_select_authenticated" on public.pomodoro_room_members;
drop policy if exists "pomodoro_room_members_insert_own" on public.pomodoro_room_members;
drop policy if exists "pomodoro_room_members_update_own" on public.pomodoro_room_members;
drop policy if exists "pomodoro_room_members_delete_own_or_owner" on public.pomodoro_room_members;

create policy "pomodoro_room_members_select_authenticated"
  on public.pomodoro_room_members
  for select
  to authenticated
  using (true);

create policy "pomodoro_room_members_insert_own"
  on public.pomodoro_room_members
  for insert
  with check (auth.uid() = user_id);

create policy "pomodoro_room_members_update_own"
  on public.pomodoro_room_members
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "pomodoro_room_members_delete_own_or_owner"
  on public.pomodoro_room_members
  for delete
  using (
    auth.uid() = user_id
    or exists (
      select 1
      from public.pomodoro_rooms r
      where r.id = room_id
        and r.owner_id = auth.uid()
    )
  );

-- 12) pomodoro_room_presence policies
drop policy if exists "pomodoro_room_presence_select_authenticated" on public.pomodoro_room_presence;
drop policy if exists "pomodoro_room_presence_insert_own" on public.pomodoro_room_presence;
drop policy if exists "pomodoro_room_presence_update_own" on public.pomodoro_room_presence;
drop policy if exists "pomodoro_room_presence_delete_own" on public.pomodoro_room_presence;

create policy "pomodoro_room_presence_select_authenticated"
  on public.pomodoro_room_presence
  for select
  to authenticated
  using (true);

create policy "pomodoro_room_presence_insert_own"
  on public.pomodoro_room_presence
  for insert
  with check (auth.uid() = user_id);

create policy "pomodoro_room_presence_update_own"
  on public.pomodoro_room_presence
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "pomodoro_room_presence_delete_own"
  on public.pomodoro_room_presence
  for delete
  using (auth.uid() = user_id);

-- 13) challenge_catalog policies
drop policy if exists "challenge_catalog_select_authenticated" on public.challenge_catalog;
drop policy if exists "challenge_catalog_no_insert" on public.challenge_catalog;
drop policy if exists "challenge_catalog_no_update" on public.challenge_catalog;
drop policy if exists "challenge_catalog_no_delete" on public.challenge_catalog;

create policy "challenge_catalog_select_authenticated"
  on public.challenge_catalog
  for select
  to authenticated
  using (is_active = true);

create policy "challenge_catalog_no_insert"
  on public.challenge_catalog
  for insert
  to authenticated
  with check (false);

create policy "challenge_catalog_no_update"
  on public.challenge_catalog
  for update
  to authenticated
  using (false)
  with check (false);

create policy "challenge_catalog_no_delete"
  on public.challenge_catalog
  for delete
  to authenticated
  using (false);

-- 14) push_subscriptions policies
drop policy if exists "push_subscriptions_select_own" on public.push_subscriptions;
drop policy if exists "push_subscriptions_insert_own" on public.push_subscriptions;
drop policy if exists "push_subscriptions_update_own" on public.push_subscriptions;
drop policy if exists "push_subscriptions_delete_own" on public.push_subscriptions;

create policy "push_subscriptions_select_own"
  on public.push_subscriptions
  for select
  using (auth.uid() = user_id);

create policy "push_subscriptions_insert_own"
  on public.push_subscriptions
  for insert
  with check (auth.uid() = user_id);

create policy "push_subscriptions_update_own"
  on public.push_subscriptions
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "push_subscriptions_delete_own"
  on public.push_subscriptions
  for delete
  using (auth.uid() = user_id);

-- 5) Indexes
create index if not exists idx_user_challenge_progress_user_id on public.user_challenge_progress (user_id);
create index if not exists idx_user_challenge_progress_completed_at on public.user_challenge_progress (completed_at desc);
create index if not exists idx_pomodoro_sessions_user_id on public.pomodoro_sessions (user_id);
create index if not exists idx_pomodoro_sessions_completed_at on public.pomodoro_sessions (completed_at desc);
create index if not exists idx_custom_challenges_user_id on public.custom_challenges (user_id);
create index if not exists idx_reward_redemptions_user_id on public.reward_redemptions (user_id);
create index if not exists idx_reward_catalog_is_active on public.reward_catalog (is_active);
create index if not exists idx_user_rewards_user_id on public.user_rewards (user_id);
create index if not exists idx_user_leaderboard_points on public.user_leaderboard (total_points desc, updated_at asc);
create index if not exists idx_pomodoro_rooms_created_at on public.pomodoro_rooms (created_at desc);
create index if not exists idx_pomodoro_room_members_user on public.pomodoro_room_members (user_id);
create index if not exists idx_pomodoro_room_presence_updated_at on public.pomodoro_room_presence (updated_at desc);
create index if not exists idx_challenge_catalog_week_day on public.challenge_catalog (week, day);
create index if not exists idx_push_subscriptions_user on public.push_subscriptions (user_id);

delete from public.reward_catalog a
using public.reward_catalog b
where a.id > b.id
  and a.title = b.title;

create unique index if not exists idx_reward_catalog_title_unique on public.reward_catalog (title);

-- 1 usuario = 1 sala (limpia duplicados antes de crear constraint)
with ranked_members as (
  select
    room_id,
    user_id,
    joined_at,
    row_number() over (partition by user_id order by joined_at desc, room_id desc) as rn
  from public.pomodoro_room_members
)
delete from public.pomodoro_room_members m
using ranked_members r
where m.room_id = r.room_id
  and m.user_id = r.user_id
  and r.rn > 1;

with ranked_presence as (
  select
    room_id,
    user_id,
    updated_at,
    row_number() over (partition by user_id order by updated_at desc, room_id desc) as rn
  from public.pomodoro_room_presence
)
delete from public.pomodoro_room_presence p
using ranked_presence r
where p.room_id = r.room_id
  and p.user_id = r.user_id
  and r.rn > 1;

create unique index if not exists idx_pomodoro_room_members_user_unique on public.pomodoro_room_members (user_id);
create unique index if not exists idx_pomodoro_room_presence_user_unique on public.pomodoro_room_presence (user_id);

with ranked_rooms as (
  select
    id,
    owner_id,
    created_at,
    row_number() over (partition by owner_id order by created_at desc, id desc) as rn
  from public.pomodoro_rooms
)
delete from public.pomodoro_rooms r
using ranked_rooms rr
where r.id = rr.id
  and rr.rn > 1;

create unique index if not exists idx_pomodoro_rooms_owner_unique on public.pomodoro_rooms (owner_id);

insert into public.reward_catalog (title, description, cost_points)
values
  ('Bono Kokoriko', 'Cupon de ejemplo para redimir en aliados.', 120),
  ('Tema premium', 'Desbloquea una apariencia premium en la app.', 80),
  ('Descanso extendido', 'Canjea un break de 30 minutos sin culpa.', 60)
on conflict (title) do nothing;

insert into public.challenge_catalog (code, title, description, week, day, points, is_active)
values
  ('atencion-01', 'Elegir una red social y limitar su uso a 15 minutos diarios.', 'Registrar el tiempo de uso diario de una red social.', 1, 1, 20, true),
  ('atencion-02', 'Definir una zona o momento libre de redes y anotar cumplimiento.', 'Anotar cuantas veces cumples y que hiciste en su lugar.', 1, 2, 20, true),
  ('atencion-03', 'Elegir 3 comportamientos que quieren reducir.', 'Ejemplo: checking compulsivo, comparacion o rage-scrolling.', 1, 3, 25, true),
  ('atencion-04', 'Elegir 60 minutos seguidos sin redes sociales.', 'Anotar que hiciste y como te sentiste en ese bloque.', 1, 4, 30, true),
  ('atencion-05', 'Desactiva todas las notificaciones no esenciales durante 3 horas.', 'Mantener 3 horas sin interrupciones de notificaciones.', 1, 5, 35, true),
  ('atencion-06', 'Crear una lista de 5 actividades offline y probar al menos 2.', 'Registrar que tan satisfactorias fueron las actividades.', 1, 6, 20, true),
  ('atencion-07', 'Revision semanal: identificar que patron se repite.', 'Detectar el patron principal de distraccion de la semana.', 1, 7, 25, true),
  ('atencion-08', 'Sin redes en clase, solo lo necesario para estudiar.', 'Reducir uso de redes durante clase o bloque de estudio.', 2, 8, 35, true),
  ('atencion-09', 'Primeros 20 minutos del dia sin pantallas.', 'Estirar, respirar o beber agua antes de ver pantallas.', 2, 9, 30, true),
  ('atencion-10', 'Utiliza el pomodoro de la aplicacion al realizar tus tareas.', 'Ajustar el pomodoro segun tus necesidades de enfoque.', 2, 10, 35, true),
  ('atencion-11', 'Invita a un amigo a hacer el reto contigo.', 'Sumar compania y compromiso en el proceso.', 2, 11, 40, true),
  ('atencion-12', 'Reduce tu tiempo en pantalla un 50% de lo normal.', 'Comparar tu tiempo actual con tu promedio habitual.', 2, 12, 35, true),
  ('atencion-13', 'Hacer una lista de 5 cosas que logre hoy.', 'Escribir avances concretos del dia.', 2, 13, 40, true),
  ('atencion-14', 'Revision semanal: que me hizo sentir mejor fuera de redes.', 'Definir que uso de redes quiero cambiar.', 2, 14, 45, true),
  ('atencion-15', 'Reemplaza 30 minutos de redes por otra actividad.', 'Usar ese tiempo en una actividad offline de valor.', 3, 15, 50, true),
  ('atencion-16', 'Haz 2 bloques de enfoque de 25 minutos cada uno.', 'Completar dos ciclos de foco con descansos breves.', 3, 16, 45, true),
  ('atencion-17', '30 minutos antes de dormir, desconectate de todas las pantallas.', 'Preparar descanso sin estimulos digitales.', 3, 17, 45, true),
  ('atencion-18', 'Elegir 1 dia de la semana como dia ligero en redes.', 'Maximo 30 minutos en redes durante ese dia.', 3, 18, 40, true),
  ('atencion-19', 'Usar distintas plataformas solo para aprender cosas nuevas.', 'Consumir contenido educativo de forma intencional.', 3, 19, 50, true),
  ('atencion-20', 'Practicar un hobby externo a las redes.', 'Dedicar tiempo a un habito offline significativo.', 3, 20, 35, true),
  ('atencion-21', 'Plan post-reto: escribe 3 reglas para tu uso de redes.', 'Definir reglas personales para sostener el cambio.', 3, 21, 60, true)
on conflict (code) do update
set
  title = excluded.title,
  description = excluded.description,
  week = excluded.week,
  day = excluded.day,
  points = excluded.points,
  is_active = excluded.is_active;

create or replace function public.get_email_by_nickname(nickname_input text)
returns text
language sql
security definer
set search_path = public, auth
as $$
  select email
  from auth.users
  where lower(coalesce(raw_user_meta_data->>'nickname', raw_user_meta_data->>'full_name', '')) = lower(nickname_input)
  limit 1;
$$;

revoke all on function public.get_email_by_nickname(text) from public;
grant execute on function public.get_email_by_nickname(text) to anon, authenticated;

-- Seed de ranking con usuarios existentes en auth.users
-- Nota: requiere que existan usuarios autenticados para insertar por FK.
insert into public.user_leaderboard (user_id, display_name, total_points, updated_at)
select
  u.id,
  coalesce(nullif(u.raw_user_meta_data->>'nickname', ''), nullif(u.raw_user_meta_data->>'full_name', ''), split_part(u.email, '@', 1), 'Usuario') as display_name,
  greatest(0, 260 - ((row_number() over (order by u.created_at asc) - 1) * 35))::integer as total_points,
  now()
from auth.users u
where u.email is not null
order by u.created_at asc
limit 12
on conflict (user_id) do update
set
  display_name = excluded.display_name,
  total_points = greatest(public.user_leaderboard.total_points, excluded.total_points),
  updated_at = now();
